POST http://localhost:3030/videos
Content-Type: application/json


{
    "title": "Video 1",
    "description": "primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3030/videos?search=node
###

PUT http://localhost:3030/videos/723b39a9-0403-43b1-93f7-1799f6f5f02c
Content-Type: application/json


{
    "title": "marcelo",
    "description": "primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3030/videos/7e82087c-e596-4227-943f-9dc9ff39e502